### ISSUE TITLE
With TenantId provided in the parameter, it still ask for tenantId

### ISSUE THREAD

**Issue by matthewygf** [NAVPERF/NAV2017-Sample#1]
orderProcessorUserContextManager = new NAVUserContextManager(
                       address,
                       "Default",
                       null,
                       OrderProcessorRoleCenterId,
                       username,
                       password);

A tenant was not specified, but is needed because the system has multiple tenants. Contact your system administrator.

But if i go to the url "https://webclienUrl/?Tenant=Default" it will work in my browser.

**Comment by freddydk** [comment]
You can read here: https://blogs.msdn.microsoft.com/freddyk/2016/12/17/perf-testing-with-multiple-users/ how to work with multiple tenants.
