### ISSUE TITLE
System.InvalidOperationException: Message was shown

### ISSUE THREAD

**Issue by AmandaTest** [NAVPERF/NAV2017-Sample#3]
I am not able to Save bool as true on any form. System.InvalidOperationException: Message was shown.

In my example, I try to set the "Action Line" bool field on the Container Worksheet Journal page = true.

            ContainerWorksheetPage.Control("Container Details").Activate();
            ContainerWorksheetPage.Control("Action Line").Activate();
            ContainerWorksheetPage.Control("Action Line").SaveValue(true);

**Comment by freddydk** [comment]
I will have a look today.

**Comment by freddydk** [comment]
Just tried to set a boolean field on the Sales Order page, using:
  var vatControl = newSalesOrderPage.Control("Prices Including VAT");
  vatControl.SaveValue(true);
works fine.

The Container Worksheet Journal Page seems to be in your solution. I cannot test there, but you should do this:
  var control = ContainerWorksheetPage.Control("Action Line");
and then set a breakpoint and validate that control is a ClientBooleanControl. If not, you might have another control on the page called Action Line and you need to modify the page or the logic in which you locate the control.

**Comment by AmandaTest** [comment]
Thank you.  Your method for setting the control works for me.
