### ISSUE TITLE
Regarding Perf test on NAV2017

### ISSUE THREAD

**Issue by gschaudhari** [NAVPERF/NAV2017-Sample#5]
Hello,

We are trying to Run the load test on NAV2017.  However i could not find http://<ServerName>/<InstanceName>/WebClient/Services/ClientService.svc in 2017 version of NAV. Could you please let me know gow can i enable it or is there any other way to connect using Visual studio apart form ClientService.svc 

Note: I have enabled "Enable Client Services" option from the "Dynamics NAV 2017 Administration" 

Thanks and Regards,
Girish

**Comment by freddydk** [comment]
This is not part of client services - it is part of the web client.
Do you have the full URL to the Web Client (also https if you have installed the WebClient with ssl) as your url?

**Comment by gschaudhari** [comment]
http://<ServerName>/<InstanceName>/WebClient/Services/ClientService.svc This is the URL for Client service. This URL is working for NAV2015, However the same URL is not working for NAV2017. I could not see C:\Program Files\Microsoft Dynamics NAV\100\Web Client\Services in NAV2017 as a result the above URL does not work. Is there any alternate way to connect the Visual studio code in NAV2017.

**Comment by freddydk** [comment]
You will need to use the NAV2017 project for NAV 2017.
In the app config of NAV 2017, the default for NAVClientService is
<setting name="NAVClientService" serializeAs="String">
    <value>http://localhost/NAV/WebClient/cs</value>
</setting>
I think that you can deduct from this that you should remove clientService/ClientService.svc and replace that with cs.

**Comment by gschaudhari** [comment]
Thanks Freddydk,

I tried using http://ServerName/InstanceName/WebClient/cs However it does not work for me.

**Comment by freddydk** [comment]
does http://ServerName/InstanceName/WebClient open the web client?
You cannot open the service endpoint in a browser.

**Comment by gschaudhari** [comment]
Thanks a lot
I could able to Open the webclient using  http://ServerName/InstanceName/WebClient. I will try this url : http://ServerName/InstanceName/WebClient/cs in the Visual studio code
