### ISSUE TITLE
Issue with the Amount field on the Payment journal screen

### ISSUE THREAD

**Issue by gschaudhari** [NAVPERF/NAV2017-Sample#6]
Hello,

I writing the case for Vendor Payment in NAV 2017, I can enter all the fields except Amount. Following is the code for the same. 

`
 var openedForm = userContext.RoleCenterPage;

            var lookupForm = openedForm.Action("Lookup").InvokeCatchDialog();

            lookupForm.Action("New Line").Invoke();

            var itemsLine = lookupForm.Repeater().DefaultViewport[0];

            itemsLine.Control("Name").Activate();

            itemsLine.Control("Description").Activate();

            //MAximum number of characters should be 10 -Name Field 

            string new_number =Convert.ToString(SafeRandom.GetRandomNext(1, 100));

            TestScenario.SaveValueAndIgnoreWarning(TestContext, userContext, itemsLine.Control("Name"), "TEST_J_"+new_number );
            TestScenario.SaveValueAndIgnoreWarning(TestContext, userContext, itemsLine.Control("Description"), "TEST_D_" +new_number);

            DelayTiming.SleepDelay(DelayTiming.ThinkDelay);

            userContext.ValidateForm(lookupForm);

            lookupForm.Action("OK").Invoke();

            openedForm.Control("Account No.").Activate();
            
            openedForm.Control("Currency Code").Activate();
            
            openedForm.Control("Amount").Activate();

            var data = openedForm.Control("Amount").StringValue;

            openedForm.Control("Bal. Account No.").Activate();
            
            TestScenario.SaveValueWithDelay(openedForm.Control("Account No."), "1000041");
            TestScenario.SaveValueWithDelay(openedForm.Control("Currency Code"), "EUR");
            TestScenario.SaveValueWithDelay(openedForm.Control("Amount"), 1000.00);
            TestScenario.SaveValueWithDelay(openedForm.Control("Bal. Account No."), "1000000");

            var data1 = openedForm.Control("Amount").StringValue;

            DelayTiming.SleepDelay(DelayTiming.ThinkDelay);

            userContext.ValidateForm(lookupForm);

            using (new TestTransaction(TestContext, "Post"))
            {
                ClientLogicalForm dialog = userContext.CatchDialog(openedForm.Action("Post").Invoke);
                if (dialog != null)
                {
                    var yesDialog = dialog.Action("Yes").InvokeCatchDialog();
                   
                }
            }

            TestScenario.ClosePage(TestContext, userContext, openedForm); 
 
 
`
When i click on the Yes button from this code after entering all the fields it does not process as i am getting error "Amount field can not be zero or empty", However i am already passing the amount as 1000 Euro.

**Comment by wortho** [comment]
Hi,

Have you tried using "SaveValueAndIgnoreWarning" instead?

Regards,

David

**Comment by gschaudhari** [comment]
Yes that also I have tried

**Comment by wortho** [comment]
Hi @gschaudhari , Did you solve the issue?

**Comment by gschaudhari** [comment]
Yes David this issue is resolved .

We need to define variable like this Decimal amountcost = 5000.00M and use
the variable name
